const CATALOG =[
  {
    id:'el1',
    name: 'Ноутбук Apple MacBook Pro 13 M1 8-core (8-core GPU)/8/256',
    img: 'img/catalog/el1.jpg',
    price: 87990,
    reviews:35,
    grade:'4,7',
  },
  {
    id:'el2',
    name: 'Беспроводные наушники с микрофоном Apple AirPods 3-го...',
    img: 'img/catalog/el2.jpg',
    price: 12990,
    reviews:198,
    grade:'4,1',
  },
  {
    id:'el3',
    name: 'Игра для PS4 CD-PROJEKT-RED Cyberpunk 2077',
    img: 'img/catalog/el3.jpg',
    price: 990,
    reviews:98,
    grade:'2,5',
  },
  {
    id:'el4',
    name: 'Ноутбук HUAWEI MateBook D 15 BoD-WDH9 8+512GB Space Grey',
    img: 'img/catalog/el4.jpg',
    price: 63990,
    reviews:421,
    grade:'4,7',
  },
  {
    id:'el5',
    name: 'Кофемашина Philips EP1220/00 Series 1200',
    img: 'img/catalog/el5.jpg',
    price: 25990,
    reviews:542,
    grade:'4,2',
  },
  {
    id:'el6',
    name: 'Смартфон Apple iPhone 11 128GB Black (MHDH3RU/A)',
    img: 'img/catalog/el6.jpg',
    price: 55990,
    reviews:938,
    grade:'4,7',
  },
  {
    id:'el7',
    name: 'Видеокарта MSI GeForce RTX 4070 Ti GAMING X TRIO',
    img: 'img/catalog/el7.jpg',
    price: 87499,
    reviews:134,
    grade:'4,0',
  },
  {
    id:'el8',
    name: 'Клавиатура проводная+беспроводная Keychron K8',
    img: 'img/catalog/el8.jpg',
    price: 10999,
    reviews:98,
    grade:'4,9',
  },
  {
    id:'el9',
    name: '28" Монитор Samsung Odyssey G7 S28AG702NI',
    img: 'img/catalog/el9.jpg',
    price: 54299,
    reviews:18,
    grade:'5,0',
  },
  {
    id:'el10',
    name: 'Мышь проводная Glorious Model O',
    img: 'img/catalog/el10.jpg',
    price: 5999,
    reviews:21,
    grade:'4,8',
  },
  {
    id:'el11',
    name: 'Проводная гарнитура HyperX Cloud Alpha HX-HSCA-RD черный',
    img: 'img/catalog/el11.jpg',
    price: 8999,
    reviews:344,
    grade:'3,9',
  },
  {
    id:'el12',
    name: 'Процессор Intel Core i5-12600KF BOX',
    img: 'img/catalog/el12.jpg',
    price: 22999,
    reviews:355,
    grade:'4,1',
  },
  
]